### ISSUE TITLE
Error while generating page

### ISSUE THREAD

**Issue by dmitriymarley** [Kunstmaan/KunstmaanBundlesStandardEdition#126] opened 2015-03-12 17:05 UTC
Hi there, i'm trying to create a homepage using kuma:generate:page, but it gives me an error:
Symfony\Component\Debug\ContextErrorException
Warning: max(): Array must contain at least one element

How can i fix this?

**Comment by arneruy** [comment] 2015-05-12 07:43
Hi dmitriymarley, I don't seem to be able to reconstruct this error, could you please tell me which PHP version you are using and send a screenshot of this error occurring?

**Comment by krispypen** [comment] 2015-06-02 14:06
Closing this issue because of no reply

**Closed by krispypen** 2015-06-02 14:06 UTC

**Comment by jmonday** [comment] 2015-07-09 18:20
I'm also getting this same error when attempting to create a new page type. I can't get a stacktrace as my terminal seems to enter an endless loop of the mentioned error:

`Warning: max(): Array must contain at least one element`

This is with a fresh install and creating a new bundle. Nothing else has been setup or configured beyond initial install. The only difference I can think of, my bundles use XML configuration rather than Yaml.

Suggestions?

**Comment by jmonday** [comment] 2015-07-09 18:28
Just tested with a fresh bundle generated with defaults from the various `kuma` commands.

`kuma:generate:bundle`
`kuma:generate:page`

Attempted to create a page with two fields:
 - name: type single line text
 - headerImage: type image

Same problem.

**Comment by jmonday** [comment] 2015-07-09 19:01
I've traced this back to when the `src/Acme/Bundle/TestBundle/Resources/config/pagetemplates` directory doesn't exist or is empty. Once I created this directory and added one page type Yaml configuration file, I could no longer reproduce the `Warning: max(): Array must contain at least one element` error.

I'm confused though, isn't this command generating one of these Yaml configuration files? Why is it asking my to select already existing page templates...?

**Comment by rcsistema** [comment] 2015-07-12 00:59
@dmitriymarley 
Hey, I did have this error when I wanted to answer with one template without comma. As a matter of fact it is expecting an array O_o So it just put 2 templates as far as I can remember and then deleted it in the class. Or maybe I just put a comma I cannot remember exactly. 
But the message was explicit enough to understand that when I was specifying only one tmplate I got that error so I guessed they didn't manage the case when user only specify one template ... which causes that error.
To be fixed in the code, but so as to make it work ... only specify 2 of them.
